import datetime

tanggal = datetime.datetime.now()

print(tanggal)
print(tanggal.strftime("%a"))
print(tanggal.strftime("%A"))
print(tanggal.strftime("%w"))
print(tanggal.strftime("%d"))
print(tanggal.strftime("%b"))
print(tanggal.strftime("%B"))
print(tanggal.strftime("%m"))
print(tanggal.strftime("%y"))
print(tanggal.strftime("%Y"))
print(tanggal.strftime("%H"))
print(tanggal.strftime("%I"))
print(tanggal.strftime("%p"))
print(tanggal.strftime("%M"))
print(tanggal.strftime("%S"))
print(tanggal.strftime("%f"))
print(tanggal.strftime("%j"))
print(tanggal.strftime("%U"))
print(tanggal.strftime("%W"))
print(tanggal.strftime("%c"))
print(tanggal.strftime("%C"))
print(tanggal.strftime("%x"))
print(tanggal.strftime("%X"))
print(tanggal.strftime("%G"))
print(tanggal.strftime("%V"))
